import type { ExperienceData } from '../schemas';

export const EMERALD_MINING_DATA: ExperienceData = {
  config: {
    id: 'emeraldMining',
    title: 'experiences.emeraldMining.title',
    subtitle: 'experiences.emeraldMining.subtitle',
    description: 'experiences.emeraldMining.description',
    experiencePricePerPerson: 350000,
    numberOfNights: 1,
    depositPercent: 15,
    maxPeople: 10,
    minPeople: 1,
    images: {
      heroBackground: '/assets/images/hero/h10.webp',
      valuePropositionTile1: '/assets/images/hero/h10.webp',
      valuePropositionTile2: '/assets/images/hero/h7.webp',
      valuePropositionTile3: '/assets/images/hero/h8.webp',
    },
    includesItems: [
      'experiences.emeraldMining.includes.guide',
      'experiences.emeraldMining.includes.equipment',
      'experiences.emeraldMining.includes.transport',
      'experiences.emeraldMining.includes.insurance',
    ],
    includesFullDetails: 'experiences.emeraldMining.includesFullDetails',
    microcopy: {
      deposit: 'experiences.common.deposit',
      balance: 'experiences.common.balance',
      security: 'experiences.common.security',
      ctaPrimary: 'experiences.common.ctaPrimary',
      ctaSecondary: 'experiences.common.ctaSecondary',
    },
    logistics: [
      { id: 'start', icon: 'clock', label: 'experiences.emeraldMining.logistics.start', value: '11:00 AM' },
      { id: 'duration', icon: 'hourglass', label: 'experiences.emeraldMining.logistics.duration', value: '2 Days / 1 Night' },
      { id: 'transport', icon: 'car', label: 'experiences.emeraldMining.logistics.transport', value: '4x4 Included' },
      { id: 'difficulty', icon: 'activity', label: 'experiences.emeraldMining.logistics.difficulty', value: 'Moderate' },
    ],
    included: [
      { id: 'guide', title: 'experiences.emeraldMining.included.guide' },
      { id: 'equipment', title: 'experiences.emeraldMining.included.equipment' },
      { id: 'meals', title: 'experiences.emeraldMining.included.meals' },
      { id: 'insurance', title: 'experiences.emeraldMining.included.insurance' },
    ],
    notIncluded: [
      { id: 'accommodation', title: 'experiences.emeraldMining.notIncluded.accommodation' },
      { id: 'drinks', title: 'experiences.emeraldMining.notIncluded.drinks' },
      { id: 'souvenirs', title: 'experiences.emeraldMining.notIncluded.souvenirs' },
    ],
    location: {
      lat: 4.8699,
      lng: -73.2897,
      label: 'Chivor, Boyacá, Colombia',
      zoom: 13,
    },
    host: {
      name: 'Carlos',
      avatarUrl: '/assets/images/hero/h7.webp',
      bio: 'experiences.emeraldMining.host.bio',
      idealForItems: [
        'experiences.emeraldMining.host.idealFor1',
        'experiences.emeraldMining.host.idealFor2',
        'experiences.emeraldMining.host.idealFor3',
      ],
      goodToKnowItems: [
        'experiences.emeraldMining.host.goodToKnow1',
        'experiences.emeraldMining.host.goodToKnow2',
        'experiences.emeraldMining.host.goodToKnow3',
      ],
    },
  },
  accommodationTiers: [
    {
      id: 'heritage',
      tierTag: 'experiences.ui.experienceDetails.tierBadgeHeritage',
      tierLabel: 'experiences.tiers.heritage.name',
      tierDescription: 'experiences.tiers.heritage.desc',
      isHostChoice: true,
      images: {
        main: '/assets/images/hero/h7.webp',
        thumbnail: '/assets/images/hero/h7-thumb.webp',
        gallery: ['/assets/images/hero/h8.webp', '/assets/images/hero/h10.webp'],
      },
      quickSpecs: {
        hasPrivateBathroom: true,
        hasWifi: true,
      },
      rooms: [
        { id: 'h_std', label: 'experiences.tiers.heritage.rooms.standard', capacity: 2, pricePerNight: 120000 },
        { id: 'h_fam', label: 'experiences.tiers.heritage.rooms.family', capacity: 4, pricePerNight: 180000 },
      ],
      services: [
        { id: 'breakfast', label: 'experiences.tiers.heritage.services.breakfast', pricePerPersonPerNight: 25000 },
        { id: 'dinner', label: 'experiences.tiers.heritage.services.dinner', pricePerPersonPerNight: 45000 },
      ],
      roundtripTransfer: { origin: 'Bogotá', destination: 'Chivor', pricePerVehicle: 1300000, maxPeoplePerVehicle: 4 },
      tierNote: 'experiences.tiers.heritage.tierNote',
      idealForItems: [
        'experiences.tiers.heritage.idealFor1',
        'experiences.tiers.heritage.idealFor2',
        'experiences.tiers.heritage.idealFor3',
      ],
      goodToKnowItems: [
        'experiences.tiers.heritage.goodToKnow1',
        'experiences.tiers.heritage.goodToKnow2',
      ],
      itinerary: [
        {
          day: 1,
          label: 'experiences.tiers.heritage.itinerary.day1Title',
          stops: [
            {
              time: '11:00 AM',
              title: 'experiences.tiers.heritage.itinerary.stop1Title',
              shortDescription: 'experiences.tiers.heritage.itinerary.stop1ShortDesc',
              description: 'experiences.tiers.heritage.itinerary.stop1Desc',
              imageUrl: '/assets/images/hero/h7.webp',
              images: ['/assets/images/hero/h7.webp', '/assets/images/hero/h8.webp', '/assets/images/hero/h10.webp'],
              categoryIcon: 'Gem',
            },
            {
              time: '01:00 PM',
              title: 'experiences.tiers.heritage.itinerary.stop2Title',
              shortDescription: 'experiences.tiers.heritage.itinerary.stop2ShortDesc',
              description: 'experiences.tiers.heritage.itinerary.stop2Desc',
              imageUrl: '/assets/images/hero/h8.webp',
              images: ['/assets/images/hero/h8.webp', '/assets/images/hero/h7.webp', '/assets/images/hero/h10.webp'],
              categoryIcon: 'Search',
            },
            {
              time: '04:30 PM',
              title: 'experiences.tiers.heritage.itinerary.stop3Title',
              shortDescription: 'experiences.tiers.heritage.itinerary.stop3ShortDesc',
              description: 'experiences.tiers.heritage.itinerary.stop3Desc',
              imageUrl: '/assets/images/hero/h7.webp',
              images: ['/assets/images/hero/h7.webp', '/assets/images/hero/h8.webp'],
              categoryIcon: 'Hotel',
            },
          ],
        },
        {
          day: 2,
          label: 'experiences.tiers.heritage.itinerary.day2Title',
          stops: [
            {
              time: '08:00 AM',
              title: 'experiences.tiers.heritage.itinerary.stop4Title',
              shortDescription: 'experiences.tiers.heritage.itinerary.stop4ShortDesc',
              description: 'experiences.tiers.heritage.itinerary.stop4Desc',
              imageUrl: '/assets/images/hero/h7.webp',
              images: ['/assets/images/hero/h7.webp', '/assets/images/hero/h8.webp'],
              categoryIcon: 'Coffee',
            },
            {
              time: '10:00 AM',
              title: 'experiences.tiers.heritage.itinerary.stop5Title',
              shortDescription: 'experiences.tiers.heritage.itinerary.stop5ShortDesc',
              description: 'experiences.tiers.heritage.itinerary.stop5Desc',
              imageUrl: '/assets/images/hero/h8.webp',
              images: ['/assets/images/hero/h8.webp', '/assets/images/hero/h7.webp'],
              categoryIcon: 'BookOpen',
            },
            {
              time: '02:00 PM',
              title: 'experiences.tiers.heritage.itinerary.stop6Title',
              shortDescription: 'experiences.tiers.heritage.itinerary.stop6ShortDesc',
              description: 'experiences.tiers.heritage.itinerary.stop6Desc',
              images: ['/assets/images/hero/h7.webp', '/assets/images/hero/h8.webp', '/assets/images/hero/h10.webp'],
              categoryIcon: 'Award',
            },
          ],
        },
      ],
    },
    {
      id: 'adventure',
      tierTag: 'experiences.ui.experienceDetails.tierBadgeAdventure',
      tierLabel: 'experiences.tiers.adventure.name',
      tierDescription: 'experiences.tiers.adventure.desc',
      images: {
        main: '/assets/images/hero/h10.webp',
        thumbnail: '/assets/images/hero/h10-thumb.webp',
        gallery: ['/assets/images/hero/h11.webp'],
      },
      quickSpecs: {
        hasPrivateBathroom: true,
        hasWifi: false,
      },
      rooms: [
        { id: 'g_dome', label: 'experiences.tiers.adventure.rooms.dome', capacity: 2, pricePerNight: 250000 },
      ],
      roundtripTransfer: { origin: 'Bogotá', destination: 'Chivor', pricePerVehicle: 1500000, maxPeoplePerVehicle: 4 },
      tierNote: 'experiences.tiers.adventure.tierNote',
      idealForItems: [
        'experiences.tiers.adventure.idealFor1',
        'experiences.tiers.adventure.idealFor2',
        'experiences.tiers.adventure.idealFor3',
      ],
      goodToKnowItems: [
        'experiences.tiers.adventure.goodToKnow1',
        'experiences.tiers.adventure.goodToKnow2',
      ],
      itinerary: [
        {
          day: 1,
          label: 'experiences.tiers.adventure.itinerary.day1Title',
          stops: [
            {
              time: '11:00 AM',
              title: 'experiences.tiers.adventure.itinerary.stop1Title',
              shortDescription: 'experiences.tiers.adventure.itinerary.stop1ShortDesc',
              description: 'experiences.tiers.adventure.itinerary.stop1Desc',
              imageUrl: '/assets/images/hero/h10.webp',
              images: ['/assets/images/hero/h10.webp', '/assets/images/hero/h11.webp', '/assets/images/hero/h8.webp'],
              categoryIcon: 'Gem',
            },
            {
              time: '01:00 PM',
              title: 'experiences.tiers.adventure.itinerary.stop2Title',
              shortDescription: 'experiences.tiers.adventure.itinerary.stop2ShortDesc',
              description: 'experiences.tiers.adventure.itinerary.stop2Desc',
              imageUrl: '/assets/images/hero/h11.webp',
              images: ['/assets/images/hero/h11.webp', '/assets/images/hero/h10.webp'],
              categoryIcon: 'Search',
            },
            {
              time: '05:00 PM',
              title: 'experiences.tiers.adventure.itinerary.stop3Title',
              shortDescription: 'experiences.tiers.adventure.itinerary.stop3ShortDesc',
              description: 'experiences.tiers.adventure.itinerary.stop3Desc',
              imageUrl: '/assets/images/hero/h10.webp',
              images: ['/assets/images/hero/h10.webp', '/assets/images/hero/h11.webp'],
              categoryIcon: 'Hotel',
            },
          ],
        },
        {
          day: 2,
          label: 'experiences.tiers.adventure.itinerary.day2Title',
          stops: [
            {
              time: '07:30 AM',
              title: 'experiences.tiers.adventure.itinerary.stop4Title',
              shortDescription: 'experiences.tiers.adventure.itinerary.stop4ShortDesc',
              description: 'experiences.tiers.adventure.itinerary.stop4Desc',
              imageUrl: '/assets/images/hero/h10.webp',
              images: ['/assets/images/hero/h10.webp', '/assets/images/hero/h11.webp'],
              categoryIcon: 'Coffee',
            },
            {
              time: '10:00 AM',
              title: 'experiences.tiers.adventure.itinerary.stop5Title',
              shortDescription: 'experiences.tiers.adventure.itinerary.stop5ShortDesc',
              description: 'experiences.tiers.adventure.itinerary.stop5Desc',
              imageUrl: '/assets/images/hero/h11.webp',
              images: ['/assets/images/hero/h11.webp', '/assets/images/hero/h10.webp', '/assets/images/hero/h8.webp'],
              categoryIcon: 'BookOpen',
            },
            {
              time: '02:00 PM',
              title: 'experiences.tiers.adventure.itinerary.stop6Title',
              shortDescription: 'experiences.tiers.adventure.itinerary.stop6ShortDesc',
              description: 'experiences.tiers.adventure.itinerary.stop6Desc',
              images: ['/assets/images/hero/h10.webp', '/assets/images/hero/h11.webp', '/assets/images/hero/h8.webp'],
              categoryIcon: 'Award',
            },
          ],
        },
      ],
    },
  ],
  transportOptions: [
    { value: 'car_no_4x4', label: 'experiences.emeraldMining.transport.carNo4x4', description: 'experiences.emeraldMining.transport.carNo4x4Description' },
    { value: 'have_4x4', label: 'experiences.emeraldMining.transport.have4x4', description: 'experiences.emeraldMining.transport.have4x4Description' },
    { value: 'bus', label: 'experiences.emeraldMining.transport.bus', description: 'experiences.emeraldMining.transport.busDescription' },
    { value: 'roundtrip_transfer', label: 'experiences.emeraldMining.transport.roundtripTransfer', description: 'experiences.emeraldMining.transport.roundtripTransferDescription' },
  ],
  roomModes: [
    { value: 'standard_single', label: 'experiences.emeraldMining.roomMode.standardSingle', price_multiplier: 1, fixed_people: 1, room_type_id: 'standard', units_available: 3, tier_id: 'heritage' },
    { value: 'standard_couple', label: 'experiences.emeraldMining.roomMode.standardCouple', price_multiplier: 1.1, fixed_people: 2, room_type_id: 'standard', units_available: 3, tier_id: 'heritage' },
    { value: 'family_single', label: 'experiences.emeraldMining.roomMode.familySingle', price_multiplier: 1.05, fixed_people: 1, room_type_id: 'family', units_available: 1, tier_id: 'heritage' },
    { value: 'family_couple', label: 'experiences.emeraldMining.roomMode.familyCouple', price_multiplier: 1.05, fixed_people: 2, room_type_id: 'family', units_available: 1, tier_id: 'heritage' },
    { value: 'family_3', label: 'experiences.emeraldMining.roomMode.familyThree', price_multiplier: 1.1, fixed_people: 3, room_type_id: 'family', units_available: 1, tier_id: 'heritage' },
    { value: 'cabin_single', label: 'experiences.emeraldMining.roomMode.cabinSingle', price_multiplier: 1.2, fixed_people: 1, room_type_id: 'cabin', units_available: 1, tier_id: 'adventure' },
    { value: 'cabin_couple', label: 'experiences.emeraldMining.roomMode.cabinCouple', price_multiplier: 1.2, fixed_people: 2, room_type_id: 'cabin', units_available: 1, tier_id: 'adventure' },
    { value: 'cabin_6', label: 'experiences.emeraldMining.roomMode.cabinSix', price_multiplier: 1.3, fixed_people: 6, room_type_id: 'cabin', units_available: 1, tier_id: 'adventure' },
  ],
  availableDates: [
    { id: 'apr-11-2026', startDate: '2026-04-11T00:00:00.000Z', spots: 5, isAvailable: true },
    { id: 'apr-18-2026', startDate: '2026-04-18T00:00:00.000Z', spots: 4, isAvailable: true },
    { id: 'apr-25-2026', startDate: '2026-04-25T00:00:00.000Z', spots: 3, isAvailable: true },
    { id: 'may-02-2026', startDate: '2026-05-02T00:00:00.000Z', spots: 6, isAvailable: true },
    { id: 'may-09-2026', startDate: '2026-05-09T00:00:00.000Z', spots: 5, isAvailable: true },
    { id: 'may-16-2026', startDate: '2026-05-16T00:00:00.000Z', spots: 4, isAvailable: true },
    { id: 'may-23-2026', startDate: '2026-05-23T00:00:00.000Z', spots: 3, isAvailable: true },
  ],
  whatsappLink: 'https://wa.me/573142730360?text=Hola%2C%20quiero%20reservar%20la%20Aventura%20de%20Miner%C3%ADa%20de%20Esmeraldas',
};
